object Config{
    const val compileSdkVersion = 31
    const val buildToolsVersion = "31.0.2"
    const val ndkVersion="24.0.8215888"
    const val applicationId="com.kongpf8848.dmail"
    const val minSdkVersion = 24
    const val targetSdkVersion =31
    const val versionCode = 1
    const val versionName = "0.0.1"
}

object Versions {

    const val PLUGIN_GRADLE_VERSION="7.2.1"
    const val PLUGIN_GOOGLE_SERVICE_VERSION = "4.3.10"
    const val PLUGIN_FIREBASE_CRASHLYTICS_VERSION = "2.4.1"
    const val PLUGIN_PROTOBUF_VERSION="0.8.8"
    const val KOTLIN_VERSION = "1.4.10"

    const val ANDROIDX_APP_COMPAT_VERSION = "1.2.0"
    const val ANDROIDX_LEGACY_V4_VERSION = "1.0.0"
    const val ANDROIDX_LEGACY_V13_VERSION = "1.0.0"
    const val ANDROIDX_MULTIDEX_VERSION = "2.0.1"
    const val ANDROIDX_MATERIAL_VERSION = "1.0.0"
    const val ANDROIDX_RECYCLERVIEW_VERSION = "1.1.0"
    const val ANDROIDX_PREFERENCE_VERSION = "1.1.1"
    const val ANDROIDX_CARDVIEW_VERSION = "1.0.0"
    const val ANDROIDX_GRIDLAYOUT_VERSION = "1.0.0"
    const val ANDROIDX_ANNOTATION_VERSION = "1.1.0"
    const val ANDROIDX_CONSTRAINTLAYOUT_VERSION = "2.0.1"
    const val ANDROIDX_PAGING_VERSION = "2.1.2"
    const val ANDROIDX_WORK_RUNTIME_VERSION = "2.4.0"
    const val ANDROIDX_CORE_VERSION="1.3.2"
    const val ANDROIDX_CORE_KTX_VERSION="1.3.2"
    const val ANDROIDX_ROOM_VERSION="2.2.5"
    const val ANDROIDX_COORDINATORLAYOUT_VERSION="1.1.0"
    const val ANDROIDX_DATABINDING_VERSION="4.1.0"
    const val ANDROIDX_ACTIVITY_VERSION="1.2.0-alpha06"
    const val ANDROIDX_FRAGMENT_VERSION="1.3.0-alpha06"
    const val ANDROIDX_LIFECYCLE_VERSION="2.2.0"
    const val ANDROIDX_LIFECYCLE_ARCH_VERSION="2.1.0"
    const val ANDROIDX_VIEWPAGER_VERSION="1.1.0"
    const val ANDROIDX_VIEWPAGER2_VERSION="1.0.0"
    const val ANDROIDX_EXIFINTERFACE_VERSION="1.2.0"
    const val ANDROIDX_WEBKIT_VERSION="1.3.0"

    const val ALICLOUD_ANDROID_PUSH_VERSION="3.7.3"

    const val JUNIT_VERSION = "4.12"
    const val JUNIT_EXTENSION_VERSION="1.1.5"
    const val ESPRESSO_VERSION="3.5.1"
    const val GREENDAO_VERSION="3.3.0"
    const val GOOGLE_FIREBASE_MESSAGING_VERSION = "17.6.0"
    const val GOOGLE_FIREBASE_ANALYTICS_VERSION="18.0.3"
    const val GOOGLE_FIREBASE_CRASHLYTICS_VERSION="18.0.1"
    const val JSOUP_VERSION = "1.12.1"
    const val ANDROID_PDF_VIEWER_VERSION="2.8.2"
    const val ICAL4J_VERSION="3.0.18"
    const val BACKPORT_UTIL_CONCURRENT_VERSION="3.1"
    const val COMMONS_CODEC_VERSION="1.11"
    const val COMMONS_LANG_VERSION="2.6"
    const val IMMERSIONBAR_VERSION = "3.0.0"
    const val ANNOTATIONS_API_VERSION="6.0.53"
    const val APPARA_FRAMEWORK_CORE_VERSION="19.0.6"
    const val APPARA_OPEN_COMMON_VERSION="19.0.2"
    const val APPARA_ANALYTICS_VERSION="19.0.9"
    const val MOPUB_SDK_VERSION="5.11.1"
    const val PLAY_SERVICES_ADS_VERSION="20.6.0"
    const val FACEBOOK_VERSION="6.3.0.1"
    const val GLIDE_VERSION = "4.12.0"
    const val OKHTTP_VERSION = "4.9.0"
    const val PLAY_SERVICES_AUTH_VERSION="20.4.0"
    const val RXJAVA2_VERSION = "2.2.14"
    const val RXANDROID_VERSION = "2.1.1"
    const val RETROFIT_VERSION = "2.9.0"
    const val RXPERMISSIONS_VERSION="0.10.2"
    const val BASEQUICKADAPTER_VERSION = "2.9.47"
    const val EVENTBUS_VERSION = "3.3.1"
    const val TINYPINYIN_VERSION = "2.0.3"
    const val DD_PLIST_VERSION="1.23"
    const val FLEXBOX_VERSION="1.0.0"
    const val EMOJI_JAVA_VERSION="5.1.1"
    const val IMAGEZOOM_VERSION="1.0.4"
    const val PICASSO_VERSION="2.5.2"
    const val SKETCH_GIF_VERSION="2.7.1"
    const val TOMCAT_ANNOTATIONS_API_VERSION="6.0.53"
    const val AUTODISPOSE_VERSION="1.4.0"
    const val JAVAX_MAIL_VERSION="1.6.2"
    const val APP_AUTH_VERSION = "0.11.1"
    const val LOTTIE_VERSION="5.2.0"
    const val AROUTER_VERSION = "1.5.1"
    const val AROUTER_COMPILER_VERSION = "1.2.1"
    const val BILLING_VERSION = "5.1.0"
    const val LEAK_CANARY_VERSION="2.10"
    const val EWS_API_VERSION="2.0"
}

object BuildDependencies {

    const val junit = "junit:junit:${Versions.JUNIT_VERSION}"
    const val immersionbar = "com.gyf.immersionbar:immersionbar:${Versions.IMMERSIONBAR_VERSION}"
    const val aliyunPush="com.aliyun.ams:alicloud-android-push:${Versions.ALICLOUD_ANDROID_PUSH_VERSION}"
    const val huaweiPush="com.aliyun.ams:alicloud-android-third-push-huawei:${Versions.ALICLOUD_ANDROID_PUSH_VERSION}"
    const val xiaomiPush="com.aliyun.ams:alicloud-android-third-push-xiaomi:${Versions.ALICLOUD_ANDROID_PUSH_VERSION}"
    const val oppoPush="com.aliyun.ams:alicloud-android-third-push-oppo:${Versions.ALICLOUD_ANDROID_PUSH_VERSION}"
    const val googlePush="com.aliyun.ams:alicloud-android-third-push-fcm:${Versions.ALICLOUD_ANDROID_PUSH_VERSION}"

    const val kotlinStdlib = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.KOTLIN_VERSION}"
    const val kotlinStdlibJdk7 = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Versions.KOTLIN_VERSION}"
    const val firebaseMessaging = "com.google.firebase:firebase-messaging:${Versions.GOOGLE_FIREBASE_MESSAGING_VERSION}"
    const val okhttp="com.squareup.okhttp3:okhttp:${Versions.OKHTTP_VERSION}"
    const val rxjava2 = "io.reactivex.rxjava2:rxjava:${Versions.RXJAVA2_VERSION}"
    const val rxAndroid = "io.reactivex.rxjava2:rxandroid:${Versions.RXANDROID_VERSION}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.RETROFIT_VERSION}"
    const val retrofitConverterScalars= "com.squareup.retrofit2:converter-scalars:${Versions.RETROFIT_VERSION}"
    const val retrofitAdapterRxjava2 = "com.squareup.retrofit2:adapter-rxjava2:${Versions.RETROFIT_VERSION}"
    const val retrofitConverterGson = "com.squareup.retrofit2:converter-gson:${Versions.RETROFIT_VERSION}"
    const val loggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.OKHTTP_VERSION}"
    const val baseQuickAdapter = "com.github.CymChad:BaseRecyclerViewAdapterHelper:${Versions.BASEQUICKADAPTER_VERSION}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.GLIDE_VERSION}"
    const val glideCompiler = "com.github.bumptech.glide:compiler:${Versions.GLIDE_VERSION}"
    const val glideIntegration="com.github.bumptech.glide:okhttp3-integration:${Versions.GLIDE_VERSION}"
    const val jsoup = "org.jsoup:jsoup:${Versions.JSOUP_VERSION}"
    const val greendao="org.greenrobot:greendao:${Versions.GREENDAO_VERSION}"
    const val firebaseAnalytics="com.google.firebase:firebase-analytics:${Versions.GOOGLE_FIREBASE_ANALYTICS_VERSION}"
    const val firebaseCrashlytics ="com.google.firebase:firebase-crashlytics:${Versions.GOOGLE_FIREBASE_CRASHLYTICS_VERSION}"
    const val androidPdfViewer="com.github.barteksc:android-pdf-viewer:${Versions.ANDROID_PDF_VIEWER_VERSION}"
    const val ical4j="org.mnode.ical4j:ical4j:${Versions.ICAL4J_VERSION}"
    const val backport="backport-util-concurrent:backport-util-concurrent:${Versions.BACKPORT_UTIL_CONCURRENT_VERSION}"
    const val commonCodec="commons-codec:commons-codec:${Versions.COMMONS_CODEC_VERSION}"
    const val commonLang="commons-lang:commons-lang:${Versions.COMMONS_LANG_VERSION}"
    const val tomcatApi="org.apache.tomcat:annotations-api:${Versions.TOMCAT_ANNOTATIONS_API_VERSION}"
    const val apparaFrameworkCore="com.appara:appara-framework-core:${Versions.APPARA_FRAMEWORK_CORE_VERSION}"
    const val apparaOpenCommon="com.appara:appara-open-common:${Versions.APPARA_OPEN_COMMON_VERSION}"
    const val apparaAnalytics="com.appara:appara-analytics:${Versions.APPARA_ANALYTICS_VERSION}"
    const val mopubSdk="com.mopub:mopub-sdk:${Versions.MOPUB_SDK_VERSION}"
    const val playServicesAds="com.google.android.gms:play-services-ads:${Versions.PLAY_SERVICES_ADS_VERSION}"
    const val facebook="com.google.ads.mediation:facebook:${Versions.FACEBOOK_VERSION}"
    const val playServicesAuth="com.google.android.gms:play-services-auth:${Versions.PLAY_SERVICES_AUTH_VERSION}"
    const val picasso="com.squareup.picasso:picasso:${Versions.PICASSO_VERSION}"
    const val imagezoom="it.sephiroth.android.library.imagezoom:library:${Versions.IMAGEZOOM_VERSION}"
    const val sketchGif="me.panpf:sketch-gif:${Versions.SKETCH_GIF_VERSION}"
    const val rxpermissions="com.github.tbruyelle:rxpermissions:${Versions.RXPERMISSIONS_VERSION}"
    const val eventbus="org.greenrobot:eventbus:${Versions.EVENTBUS_VERSION}"
    const val tinypinyin="com.github.promeg:tinypinyin:${Versions.TINYPINYIN_VERSION}"
    const val ddPlist="com.googlecode.plist:dd-plist:${Versions.DD_PLIST_VERSION}"
    const val flexbox="com.google.android:flexbox:${Versions.FLEXBOX_VERSION}"
    const val emoji="com.vdurmont:emoji-java:${Versions.EMOJI_JAVA_VERSION}"
    const val autodispose= "com.uber.autodispose:autodispose-android-archcomponents:${Versions.AUTODISPOSE_VERSION}"
    const val javaxmail="com.sun.mail:javax.mail:${Versions.JAVAX_MAIL_VERSION}"
    const val appAuth="net.openid:appauth:${Versions.APP_AUTH_VERSION}"
    const val lottie="com.airbnb.android:lottie:${Versions.LOTTIE_VERSION}"
    const val aRouterApi="com.alibaba:arouter-api:${Versions.AROUTER_VERSION}"
    const val aRouterCompiler="com.alibaba:arouter-compiler:${Versions.AROUTER_COMPILER_VERSION}"
    const val billing="com.android.billingclient:billing:${Versions.BILLING_VERSION}"
    const val leakCanary="com.squareup.leakcanary:leakcanary-android:${Versions.LEAK_CANARY_VERSION}"
    const val ewsApi="com.microsoft.ews-java-api:ews-java-api:${Versions.EWS_API_VERSION}"

}

object AndroidX {
    const val appCompat = "androidx.appcompat:appcompat:${Versions.ANDROIDX_APP_COMPAT_VERSION}"
    const val legacyV4 = "androidx.legacy:legacy-support-v4:${Versions.ANDROIDX_LEGACY_V4_VERSION}"
    const val legacyV13 = "androidx.legacy:legacy-support-v13:${Versions.ANDROIDX_LEGACY_V13_VERSION}"
    const val multidex = "androidx.multidex:multidex:${Versions.ANDROIDX_MULTIDEX_VERSION}"
    const val material = "com.google.android.material:material:${Versions.ANDROIDX_MATERIAL_VERSION}"
    const val recyclerview = "androidx.recyclerview:recyclerview:${Versions.ANDROIDX_RECYCLERVIEW_VERSION}"
    const val preference = "androidx.preference:preference:${Versions.ANDROIDX_PREFERENCE_VERSION}"
    const val cardview = "androidx.cardview:cardview:${Versions.ANDROIDX_CARDVIEW_VERSION}"
    const val gridlayout = "androidx.gridlayout:gridlayout:${Versions.ANDROIDX_GRIDLAYOUT_VERSION}"
    const val annotationX = "androidx.annotation:annotation:${Versions.ANDROIDX_ANNOTATION_VERSION}"
    const val constraintlayout = "androidx.constraintlayout:constraintlayout:${Versions.ANDROIDX_CONSTRAINTLAYOUT_VERSION}"
    const val paging = "androidx.paging:paging-runtime:${Versions.ANDROIDX_PAGING_VERSION}"
    const val work = "androidx.work:work-runtime:${Versions.ANDROIDX_WORK_RUNTIME_VERSION}"
    const val core="androidx.core:core:${Versions.ANDROIDX_CORE_VERSION}"
    const val coreKtx="androidx.core:core-ktx:${Versions.ANDROIDX_CORE_KTX_VERSION}"
    const val room="androidx.room:room-runtime:${Versions.ANDROIDX_ROOM_VERSION}"
    const val roomKtx="androidx.room:room-ktx:${Versions.ANDROIDX_ROOM_VERSION}"
    const val roomTestHelper="androidx.room:room-testing:${Versions.ANDROIDX_ROOM_VERSION}"
    const val roomCompiler="androidx.room:room-compiler:${Versions.ANDROIDX_ROOM_VERSION}"
    const val roomRxJava2= "androidx.room:room-rxjava2:${Versions.ANDROIDX_ROOM_VERSION}"
    const val coordinatorlayout="androidx.coordinatorlayout:coordinatorlayout:${Versions.ANDROIDX_COORDINATORLAYOUT_VERSION}"
    const val databindingCommon="androidx.databinding:databinding-common:${Versions.ANDROIDX_DATABINDING_VERSION}"
    const val databindingAdapters="androidx.databinding:databinding-adapters:${Versions.ANDROIDX_DATABINDING_VERSION}"
    const val databindingRuntime="androidx.databinding:databinding-runtime:${Versions.ANDROIDX_DATABINDING_VERSION}"
    const val activity="androidx.activity:activity:${Versions.ANDROIDX_ACTIVITY_VERSION}"
    const val activityKtx="androidx.activity:activity-ktx:${Versions.ANDROIDX_ACTIVITY_VERSION}"
    const val fragment="androidx.fragment:fragment:${Versions.ANDROIDX_FRAGMENT_VERSION}"
    const val fragmentKtx="androidx.fragment:fragment-ktx:${Versions.ANDROIDX_FRAGMENT_VERSION}"
    const val lifecycleViewmodelKtx="androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleLivedataKtx="androidx.lifecycle:lifecycle-livedata-ktx:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleRuntimeKtx="androidx.lifecycle:lifecycle-runtime-ktx:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleViewmodelSavedstate="androidx.lifecycle:lifecycle-viewmodel-savedstate:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleCompiler="androidx.lifecycle:lifecycle-compiler:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleCommonJava8 = "androidx.lifecycle:lifecycle-common-java8:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleService = "androidx.lifecycle:lifecycle-service:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleProcess = "androidx.lifecycle:lifecycle-process:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleReactivestreamsKtx= "androidx.lifecycle:lifecycle-reactivestreams-ktx:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val lifecycleExtensions="androidx.lifecycle:lifecycle-extensions:${Versions.ANDROIDX_LIFECYCLE_VERSION}"
    const val arcCoreTesting="androidx.arch.core:core-testing:${Versions.ANDROIDX_LIFECYCLE_ARCH_VERSION}"
    const val viewPager2="androidx.viewpager2:viewpager2:${Versions.ANDROIDX_VIEWPAGER2_VERSION}"
    const val exifinterface="androidx.exifinterface:exifinterface:${Versions.ANDROIDX_EXIFINTERFACE_VERSION}"
    const val webkit="androidx.webkit:webkit:${Versions.ANDROIDX_WEBKIT_VERSION}"
    const val junitExtension="androidx.test.ext:junit:${Versions.JUNIT_EXTENSION_VERSION}"
    const val espresso="androidx.test.espresso:espresso-core:${Versions.ESPRESSO_VERSION}"
}



